[build]
  # This will be run the site build
  command = "npm install && npm run build && chmod +x ./create-env.sh && ./create-env.sh"
  # functions build directory
  functions = "dist/functions"
  # serve all files in this directory statically
  publish = "dist/frontend"
